server:
  port: 8082
spring:
  application:
    name: farstsp
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: rootroot
    url: jdbc:mysql://47.106.249.248:3306/farst-test?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    
  redis:
    host: 39.108.165.241
    port: 6379
    timeout: 2000
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1
    password: uupredisserver123!@#